services:
  spring:
    container_name: spring-app
    image: widdle-app:prod
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: widdle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/ec2-user/postgres:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres-data:
